n1 = int(input("Digite o Primeiro Número:"))
n2 = int(input("Digite o Segundo Número:")) 
n3 = int(input("Digite o Terceiro Número:")) 
n4 = int(input("Digite o Quarto Número:")) 
n5 = int(input("Digite o Quinto Número:"))
numeros = list(filter(lambda x: x>10,[n1,n2,n3,n4,n5]))
print("Numeros maiores que 10:",numeros)
