#com array nao tava indo nao sei pq, ai fiz de um em um
n1 = int(input("Digite o Primeiro Número:"))
n2 = int(input("Digite o Segundo Número:")) 
n3 = int(input("Digite o Terceiro Número:")) 
n4 = int(input("Digite o Quarto Número:")) 
n5 = int(input("Digite o Quinto Número:"))
n6 = int(input("Digite o Sexto Número:"))
n7 = int(input("Digite o Sétimo Número:")) 
n8 = int(input("Digite o Oitavo Número:")) 
n9 = int(input("Digite o Nono Número:")) 
n10 = int(input("Digite o Décimo Número:"))
numerosPares = list(filter(lambda x: x %2 == 0 ,[n1,n2,n3,n4,n5,n6,n7,n8,n9,n10]))
print("Numeros Pares:",numerosPares)
numerosImpares = list(filter(lambda x: x %2 == 1 ,[n1,n2,n3,n4,n5,n6,n7,n8,n9,n10]))
print("Numeros Impares:",numerosImpares)